### PR TITLE
fixed mplayer streaming

### PR DESCRIPTION
**Pull request by joekiller**
this at least has nginx streaming files to mplayer.

running `python read.py rtpm://localhost:1935/castle/bowsers-castle.mp4` doesn't see to work though.

### CODE REVIEW

**Comment by loc** [comment]
what about fixing it to `rtmp://`?

**Comment by loc** [comment]
Also, I should note, playing from an RTMP stream isn't essential. If you simply pass in a file to read.py it'll run fine. Maybe setting up RTMP should be on wiki page?

**Comment by joekiller** [comment]
Lol that might work. I'll see if I typo'd it on my box

**Comment by joekiller** [comment]
@loc updated README to actually work and include use cases for streaming or file input.

**Pull request merged**
